packages:
  - demos/*

overrides:
  '@typelex/cli': link:../../AppData/Local/pnpm/global/5/node_modules/@typelex/cli
  emitter: link:../../AppData/Local/pnpm/global/5/node_modules/@typelex/emitter
  y-atproto: link:../../AppData/Local/pnpm/global/5/node_modules/y-atproto
